name: release
on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0, v2.3.1
jobs:
  release:
    name: Build and Release Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      # This builds the binaries for all platforms and then makes a tarball for each platform to be used with krew
      - name: Package for krew
        run: make package-for-krew
      - name: Update krew manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          make update-krew-manifest
          git checkout main
          git pull
          git add plugins/kubectl-doks.yaml
          git commit -m "Update krew manifest for ${{ github.ref_name }}"
          git push
      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/kubectl-doks-*tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
