name: release
on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0, v2.3.1
jobs:
  release:
    name: Build and Release Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build binaries
        run: make build-all
      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/kubectl-doks-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
